### ISSUE TITLE
f3 scoreboard stats.

### ISSUE THREAD

**Issue by hvownij** [mich-devs/3SPNRU#6]
Headshots and LG shots seemed to be mixed up.

Funny part about it is:  

It shows the proper amount of headshots you have when it is broadcasting who has the most headshots in the game going on.

f3 shows odd numbers.  Not sure how its calculating it.

This will be a bug fix for Beta - 2.

**Comment by v-k-g** [comment]
HV and I investigated this and agreed with the following.

1. LG shots are fine. Headshot fired increases at the same rate as regular LG fired because every non-headshot counts as a missed headshot. If we only counted headshot hits, your acc with headshots would always be 100 after 1 headshot.
2. All weaps seemed to be counting hits and acc % correctly but for some reason, link and mini count fires but acc % stays at 0. This issue will focus on resolving that.
3. We will create a new issue/feature to add a hit column between fired and acc columns

**Comment by hvownij** [comment]
Only thing to add to what Viking said is we need to also Flip PRIM & ALT fire for Link Gun.  Link shaft is AltFire and Plasma is Primary.  It is showing them reversed in f3.

**Comment by v-k-g** [comment]
RE: no. 2 above -- Link and Mini damage is also not showing up but it does count towards your total damage display

**Comment by hvownij** [comment]
Issue resolve!
